using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class Player : MonoBehaviour
{
    // y‘ÌŒ±‚PzfloatŒ^‚ÌjumpPower‚ğ€”õ‚µ‚æ‚¤I


    // Update is called once per frame
    void Update()
    {
        // y‘ÌŒ±‚QzJumpƒ{ƒ^ƒ“(SpaceƒL[)‚ª‰Ÿ‚³‚ê‚½‚©‚Ç‚¤‚©”»’è‚µ‚æ‚¤I
        if (Input.GetButtonDown(""))
        {
            // y‘ÌŒ±‚RzVector3‚ÌY²•ûŒü‚ÉAjumpPower‚¾‚¯ˆÚ“®‚·‚é‚æ‚¤‚Éİ’è‚µ‚æ‚¤I
            GetComponent<Rigidbody>().velocity = new Vector3(0, 0, 0);
        }
    }

    // •Ç‚É‚Ô‚Â‚©‚Á‚½‚Ìˆ—
    void OnCollisionEnter(Collision collision)
    {
        // y‘ÌŒ±‚SzƒV[ƒ“uMainv‚ğŒÄ‚Ño‚»‚¤I
        SceneManager.LoadScene("");
    }
}
